In [2]:
import numpy as np

In [14]:
# Square an Rectangle Shape Matrix

S = np.random.randn(5, 5)

R = np.random.randn(5,2)

print(S,'\n\n', R)


[[ 1.25585385 -0.82627607 -0.11654789  0.57112494 -0.48218021]
 [ 1.86592224 -1.68793762  0.27634537 -0.13273919  0.98194974]
 [ 1.32748706  2.53955342  1.14978167 -2.73286176 -1.12481274]
 [-0.61311021  1.48702574 -1.77064914  0.75479715  0.7617853 ]
 [-1.66746828 -1.13723578  0.95557903  0.8614914   0.38265558]] 

 [[ 0.07244306 -0.28210317]
 [-0.21207044 -0.15800216]
 [-1.39196678  0.83586098]
 [ 1.32645587  2.0354267 ]
 [ 0.45183935 -1.22579802]]


In [15]:
# Identity Matrix
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# Null Matrix
Z = np.zeros((4,4))

print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# Diagonal Matrix

D = np.diag([1, 2, 3, 4, 5])

print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [8]:
# Creating Triangluar Matrix from full matrix

S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)


print(S ,'\n\n\n', U ,'\n\n\n', L)


[[-0.18965986 -0.4330451   0.10473245 -1.12566426 -0.18498862]
 [ 0.76943576 -0.88024662  0.25559466  0.91505198  1.71674179]
 [-0.02661506 -0.26558631 -0.52696962 -0.72403199  0.88471579]
 [ 0.69919017  0.20463134  2.04116946 -0.24986815  0.80437941]
 [-0.48118032  0.57622089  0.35082652  1.2242135  -0.16340145]] 


 [[-0.18965986 -0.4330451   0.10473245 -1.12566426 -0.18498862]
 [ 0.         -0.88024662  0.25559466  0.91505198  1.71674179]
 [ 0.          0.         -0.52696962 -0.72403199  0.88471579]
 [ 0.          0.          0.         -0.24986815  0.80437941]
 [ 0.          0.          0.          0.         -0.16340145]] 


 [[-0.18965986  0.          0.          0.          0.        ]
 [ 0.76943576 -0.88024662  0.          0.          0.        ]
 [-0.02661506 -0.26558631 -0.52696962  0.          0.        ]
 [ 0.69919017  0.20463134  2.04116946 -0.24986815  0.        ]
 [-0.48118032  0.57622089  0.35082652  1.2242135  -0.16340145]]


In [16]:
# Matrix Concatenation 

A = np.random.randn(3, 2)
B = np.random.randn(3, 4)

C = np.concatenate((A, B), axis=1)

C
# For Concatenation the rows should match !!

array([[ 0.61318207,  0.36931268,  1.0601384 ,  0.76350801,  0.937204  ,
         0.85980076],
       [-0.46362349,  0.51381697,  0.45420521,  1.8277825 , -0.17400551,
        -0.46009279],
       [ 0.66437579,  0.8531079 ,  0.37363251, -0.28561275,  0.13775724,
         2.41307153]])

##### Matrix Addition is Commutative i.e A + B = B + A 
##### Matrix Addition is Associative i.e A + ( B + C ) = ( A + B ) + C

In [21]:
# Matrix Addition

A = np.random.randn(5, 5)
B = np.random.randn(5, 4)
C = np.random.randn(5, 4)




B + C

array([[ 0.90629012, -0.156261  ,  0.21742321,  0.31387852],
       [-2.5567235 , -2.0072156 ,  0.35676146, -3.04819017],
       [-0.25263566, -0.67347519, -0.19694817, -0.12405769],
       [ 0.36389509,  0.41592365, -1.01936654, -0.24190386],
       [-2.46845609,  1.40229685,  1.12091683, -0.41040819]])

In [25]:
## Shifting a Matrix ( Here the Matrix can only be the Square Matrix , because the Identity matrix will be square matrix we can only add  matrices with same shape)

l = 0.3
N = 5
D = np.random.randn(N , N)

D_shift = D + l * np.eye(N)

print(D_shift)

[[ 0.05186703  0.45985203  0.39216976 -0.38115427  0.00905469]
 [ 0.34533261  3.73837983 -0.38942261  0.25840213 -0.35883761]
 [ 0.41201106 -0.92460322 -0.09941797 -1.35806781  0.62083158]
 [-1.04026015 -0.46489904  1.79785039  1.29661072 -1.48283624]
 [ 0.99887353 -0.37973557  1.90590601 -0.69912247  0.94227698]]
