In [27]:
import numpy as np

In [28]:
# Square an Rectangle Shape Matrix

S = np.random.randn(5, 5)

R = np.random.randn(5,2)

print(S,'\n\n', R)


[[ 1.52475405  0.93812933  1.28346149 -0.21046811 -1.2103742 ]
 [-0.30154394 -0.08893028  0.399809    1.22181434  1.13183047]
 [-0.3590373  -0.03776263  0.62202949  0.13844477  0.6865777 ]
 [ 0.9036148   0.48788151  0.78617059 -0.28209352 -0.3122095 ]
 [ 0.74027098 -0.11942348 -0.66066347 -0.80438192 -0.24120208]] 

 [[ 0.22802858 -1.24192472]
 [ 0.33134006 -1.36834523]
 [-0.54817271 -0.84684121]
 [-0.12819326  0.90318373]
 [ 0.77624243 -0.02606907]]


In [29]:
# Identity Matrix
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# Null Matrix
Z = np.zeros((4,4))

print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
# Diagonal Matrix

D = np.diag([1, 2, 3, 4, 5])

print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [32]:
# Creating Triangluar Matrix from full matrix

S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)


print(S ,'\n\n\n', U ,'\n\n\n', L)


[[ 1.6511884  -0.18543145  0.41990518  0.04259091  0.48410602]
 [ 0.15577904  0.80704537 -1.49771452  0.16374794 -0.24852251]
 [ 0.52493669 -1.82360587  0.29877321  1.111191    1.55449163]
 [-0.52820108 -1.29132821  1.18819006  1.35928764  1.13827775]
 [ 0.96012191 -0.12412575  0.30829777  0.16080891  0.69555656]] 


 [[ 1.6511884  -0.18543145  0.41990518  0.04259091  0.48410602]
 [ 0.          0.80704537 -1.49771452  0.16374794 -0.24852251]
 [ 0.          0.          0.29877321  1.111191    1.55449163]
 [ 0.          0.          0.          1.35928764  1.13827775]
 [ 0.          0.          0.          0.          0.69555656]] 


 [[ 1.6511884   0.          0.          0.          0.        ]
 [ 0.15577904  0.80704537  0.          0.          0.        ]
 [ 0.52493669 -1.82360587  0.29877321  0.          0.        ]
 [-0.52820108 -1.29132821  1.18819006  1.35928764  0.        ]
 [ 0.96012191 -0.12412575  0.30829777  0.16080891  0.69555656]]


In [33]:
# Matrix Concatenation 

A = np.random.randn(3, 2)
B = np.random.randn(3, 4)

C = np.concatenate((A, B), axis=1)

C
# For Concatenation the rows should match !!

array([[ 0.93047296,  1.37129176, -0.33121736, -0.38006861,  1.00624836,
        -2.84500328],
       [ 0.6029323 ,  0.76911244, -0.62537668, -0.6434618 , -0.38727053,
        -1.03163234],
       [-0.25391928,  1.18119327, -0.74357439,  0.01467478,  0.78395246,
        -0.4030441 ]])

##### Matrix Addition is Commutative i.e A + B = B + A 
##### Matrix Addition is Associative i.e A + ( B + C ) = ( A + B ) + C

In [34]:
# Matrix Addition

A = np.random.randn(5, 5)
B = np.random.randn(5, 4)
C = np.random.randn(5, 4)




B + C

array([[-0.06947774, -1.34722518,  0.80305219,  1.5443919 ],
       [-0.69225257, -0.11687336,  0.86480399,  1.9612607 ],
       [-1.37524999, -0.09273982,  1.19502074,  3.08020697],
       [-0.39017198, -1.78412454, -0.3648121 , -0.2297072 ],
       [ 2.39643213, -1.74377669,  0.75801108,  2.81303761]])

In [35]:
## Shifting a Matrix ( Here the Matrix can only be the Square Matrix , because the Identity matrix will be square matrix we can only add  matrices with same shape)

l = 0.3
N = 5
D = np.random.randn(N , N)

D_shift = D + l * np.eye(N)

print(D_shift)

[[-0.40952264 -1.81960665 -0.51429291  0.68837318 -2.5862699 ]
 [-2.05218901  1.14514096  0.24202882  0.25575615  2.42131119]
 [ 1.27137545  0.98978974 -0.35696248  0.36456793 -0.45668447]
 [-1.1452229   0.3448248   0.95265918 -0.23302644 -0.41754249]
 [ 0.26605787 -0.29006578  1.14694822  1.4222499   0.62286023]]


In [36]:
# Matrix Scalar Multiplication 

s = 3

print ( s * D)

print('\n')

print(D * s)



[[-2.12856791 -5.45881996 -1.54287873  2.06511955 -7.75880971]
 [-6.15656702  2.53542288  0.72608647  0.76726845  7.26393356]
 [ 3.81412634  2.96936921 -1.97088745  1.0937038  -1.37005342]
 [-3.43566871  1.03447441  2.85797755 -1.59907932 -1.25262747]
 [ 0.7981736  -0.87019735  3.44084467  4.26674971  0.9685807 ]]


[[-2.12856791 -5.45881996 -1.54287873  2.06511955 -7.75880971]
 [-6.15656702  2.53542288  0.72608647  0.76726845  7.26393356]
 [ 3.81412634  2.96936921 -1.97088745  1.0937038  -1.37005342]
 [-3.43566871  1.03447441  2.85797755 -1.59907932 -1.25262747]
 [ 0.7981736  -0.87019735  3.44084467  4.26674971  0.9685807 ]]


In [37]:
## Distributive property  s ( A + B ) = sA + sB 

A = np.random.randn(5, 4)

B = np.random.randn(5, 4)

s = np.random.randn()

LHS = s * ( A + B )
print(s * ( A + B ))

print('\n')

RHS = s * A  + s * B 
print(s * A  + s * B )


[[-0.34748358 -1.90905272 -1.6586378   2.18731697]
 [-0.17044812  1.58164979  0.69693584  0.80549074]
 [ 0.27447686 -0.43670006  2.11981909 -0.66466353]
 [ 0.41024636 -0.28372331  1.08595933 -1.99534081]
 [-0.03934032 -0.9154657   1.37914398  0.63717206]]


[[-0.34748358 -1.90905272 -1.6586378   2.18731697]
 [-0.17044812  1.58164979  0.69693584  0.80549074]
 [ 0.27447686 -0.43670006  2.11981909 -0.66466353]
 [ 0.41024636 -0.28372331  1.08595933 -1.99534081]
 [-0.03934032 -0.9154657   1.37914398  0.63717206]]


In [38]:
## It is Distributive !!!
print(LHS - RHS)

[[-5.55111512e-17  0.00000000e+00 -2.22044605e-16 -4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  1.11022302e-16 -1.11022302e-16]
 [-5.55111512e-17  0.00000000e+00  4.44089210e-16  0.00000000e+00]
 [ 0.00000000e+00  1.66533454e-16  0.00000000e+00 -2.22044605e-16]
 [-3.46944695e-17  1.11022302e-16  2.22044605e-16  0.00000000e+00]]


In [44]:
## Be carefull with Complex Matrices !! 

C = np.array([[4+1j, 3 , 2-4j]])

print(C)

print(C.T)

print(np.transpose(C))
## when working with matlab transpose in Harmitain matrice ; In Python you need to call explicitly the Matrix

print(np.matrix(C).H)  ## This transpose fips the sign



[[4.+1.j 3.+0.j 2.-4.j]]
[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]
[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]
[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]


In [61]:
## Diagonal and Trace 

M = np.round(5 * np.random.randn(4,4))
print(M)

print('\n')

d = np.diag(M)
D = np.diag(d)
print(d )
print('\n')
print(D)

tr = np.trace(M)
print('\n')
print(tr)
print(sum(np.diag(M))) ## another way to compute trace !!

[[ 10.  -3.   2.  -2.]
 [  2.  -5.   9.  -0.]
 [ -7.   5.  -2.   1.]
 [ -7.  -1. -11.   1.]]


[10. -5. -2.  1.]


[[10.  0.  0.  0.]
 [ 0. -5.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0.  1.]]


4.0
4.0


In [79]:
## Linearity of the Trace 

A = np.round(5 * np.random.randn(4,4))

B = np.round(5 * np.random.randn(4,4))


LHS = np.trace(A) + np.trace(B)

RHS = np.trace(A+B)

print(LHS, RHS) ## This condition holds true !!

l = 3 

lhs = l * np.trace(A)

rhs = np.trace( l * A)

print(lhs, rhs) ## This condition holds true !! 



-8.0 -8.0
27.0 27.0
